/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author client
 */
public class TaxCalculator extends javax.swing.JFrame {

    /**
     * Creates new form TaxCalculator
     */
    public TaxCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        InputValue = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        TenTax = new javax.swing.JRadioButton();
        TwelveTax = new javax.swing.JRadioButton();
        EnterValue = new javax.swing.JLabel();
        €_1 = new javax.swing.JLabel();
        HighOfTax = new javax.swing.JLabel();
        BtnCalculate = new javax.swing.JButton();
        Result = new javax.swing.JLabel();
        InputResult = new javax.swing.JTextField();
        €_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputValueActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setText("Tax calculator");

        TenTax.setSelected(true);
        TenTax.setText("10% tax");
        TenTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenTaxActionPerformed(evt);
            }
        });

        TwelveTax.setText("12% tax");
        TwelveTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwelveTaxActionPerformed(evt);
            }
        });

        EnterValue.setText("Enter value:");

        €_1.setText("€");

        HighOfTax.setText("Choose high of tax:");

        BtnCalculate.setText("Calculate");
        BtnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalculateActionPerformed(evt);
            }
        });

        Result.setText("You'll get:");

        InputResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputResultActionPerformed(evt);
            }
        });

        €_2.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HighOfTax)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnterValue)
                        .addGap(18, 18, 18)
                        .addComponent(InputValue, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(€_1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TenTax, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TwelveTax))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InputResult, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(€_2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterValue)
                    .addComponent(€_1))
                .addGap(18, 18, 18)
                .addComponent(HighOfTax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenTax)
                    .addComponent(TwelveTax))
                .addGap(12, 12, 12)
                .addComponent(BtnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Result)
                    .addComponent(InputResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(€_2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputValueActionPerformed

    private void TenTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenTaxActionPerformed
        TwelveTax.setSelected(false);
    }//GEN-LAST:event_TenTaxActionPerformed

    private void TwelveTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwelveTaxActionPerformed
        TenTax.setSelected(false);
    }//GEN-LAST:event_TwelveTaxActionPerformed

    private void InputResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputResultActionPerformed

    private void BtnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalculateActionPerformed
        String StringValue = InputValue.getText();
        float ParsedValue = Float.parseFloat(StringValue);
        float ResultValue;
        
        if(TenTax.isSelected()){
            ResultValue = (ParsedValue / 100)*10;
        } else {
            ResultValue = (ParsedValue / 100)*12;
        }
        
        String result =String.valueOf(ResultValue);
        InputResult.setText(result);
    }//GEN-LAST:event_BtnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaxCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalculate;
    private javax.swing.JLabel EnterValue;
    private javax.swing.JLabel HighOfTax;
    private javax.swing.JTextField InputResult;
    private javax.swing.JTextField InputValue;
    private javax.swing.JLabel Result;
    private javax.swing.JRadioButton TenTax;
    private javax.swing.JLabel Title;
    private javax.swing.JRadioButton TwelveTax;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel €_1;
    private javax.swing.JLabel €_2;
    // End of variables declaration//GEN-END:variables
}
